START TRANSACTION;

TRUNCATE profile CASCADE;
TRUNCATE profile_attribute CASCADE;
TRUNCATE service CASCADE;
TRUNCATE release_template CASCADE;
TRUNCATE release CASCADE;
TRUNCATE release_attribute CASCADE;

COMMIT;
